export { formatDuration } from './lib/formatDuration'
export { formatNumber } from './lib/formatNumber'
export { getAverage } from './lib/getAverage'
export { getMaximum } from './lib/getMaximum'
export { getMinimum } from './lib/getMinimum'
export { getPercentile, getPercentileIndex } from './lib/getPercentile'
export { getSampleStandardDeviation } from './lib/getSampleStandardDeviation'
export { getStandardDeviation } from './lib/getStandardDeviation'
export { getSum } from './lib/getSum'
export { isValidInteger } from './lib/isValidInteger'
export { shortenValuesList } from './lib/shortenValuesList'
export { sortValues } from './lib/sortValues'
