checks:
  method-complexity:
    config:
      threshold: 7
  method-lines:
    config:
      threshold: 30
  method-count:
    config:
      threshold: 25

plugins:
  tslint:
    enabled: true
    config: tslint.json
  nodesecurity:
    enabled: true
  git-legal:
    enabled: true
  fixme:
    enabled: true
    config:
      strings:
        - FIXME
        - TODO
  shellcheck:
    enabled: true

ratings:
  paths:
    - "packages/*/lib/**/*.ts"
    - "packages/*/*.ts"
exclude_paths:
  - "packages/*/tests/"
