export { getAvailableTimeMeasurementMethods } from './lib/getAvailableTimeMeasurementMethods'
export { getTimePrecision } from './lib/getTimePrecision'
export { timeMeasurementMethods } from './lib/timeMeasurementMethods'
export { CustomTimeMeasurement } from './lib/CustomTimeMeasurement'
export { TimeGetterType } from './lib/interfaces/TimeGetterType'
export { TimeMeasurementType } from './lib/interfaces/TimeMeasurementType'
export { TimeMeasurementInterface } from './lib/interfaces/TimeMeasurementInterface'
export { TimeMeasurementMetadataInterface } from './lib/interfaces/TimeMeasurementMetadataInterface'
